Local:
  Static_profiles: "./iTerm2-static-profiles"
  SSH_base_string: "-oStrictHostKeyChecking=no -oUpdateHostKeys=yes -oServerAliveInterval=30 -oAddKeysToAgent=no"
  Con_username: False
  Bastion: False
  SSH_keys_path: "~/.ssh"
  Use_shared_key: False
  Badge_info_to_display: 
    Name: False
    Instance_key: False
    InstanceType: False
    Bastion: False
    Bastion_Con_port: False
    Bastion_Con_username: False
    Con_port: False
    Con_username: False
    Dynamic_profile_parent_name: False
    Group: False
    Id: False
    Instance_use_Bastion: False
    Instance_use_ip_public: False
    Ip_public: False
    # Iterm_tags_prefixs: ["ENV","Name"]
    # Iterm_tags_prefixs: []
    Iterm_tags_prefixs: False
    Password: False
    Platform: False
    Region: False
    SSH_key: False
    Use_shared_key: False
    VPC: False
  
AWS:
  aws_credentials_file: "~/.aws/credentials"
  Con_username: ''
  Con_port: 22
  Con_port_windows: 3389
  use_ip_public: False
  Skip_stopped: True
  exclude_accounts: []
  exclude_regions: [] # for example: ["ap-southeast-1", "ap-southeast-2","sa-east-1","ap-northeast-1","ap-northeast-2","ap-south-1"]
  use_awscli_profiles: False
  update_hosts: False
  profiles:
  #   -
  #     name: "name_of_profile"
  #     aws_access_key_id: "your_id"
  #     aws_secret_access_key: "your_key"
  #     Con_username: ''
  # -
  #     name: "sts_using_profile"
  #     aws_access_key_id: "your_id"
  #     aws_secret_access_key: "your_key"
  #     mfa_serial_number: "arn:aws:iam::123456789012:mfa/your_aws_user_on_sts_account" #if required
  #     role_arns: {
  #       dev: "arn:aws:iam::111111111111:role/iTerm_RO_from_TGT",
  #       prod: "arn:aws:iam::999999999999:role/iTerm_RO_from_TGT",
  #     }

DO:
  Skip_stopped: True
  profiles:
  #   -
  #     name: "name_of_profile"
  #     token: "secretspecialuniquesnowflake"