Local:
  static_profiles: "./iTerm2-static-profiles"

AWS:
  aws_credentials_file: "~/.aws/credentials"
  use_ip_public: False
  skip_stopped: True
  exclude_accounts: []
  exclude_regions: [] # for example: ["ap-southeast-1", "ap-southeast-2","sa-east-1","ap-northeast-1","ap-northeast-2","ap-south-1"]
  use_awscli_profiles: False
  update_hosts: False
  profiles:
  #   -
  #     name: "name_of_profile"
  #     aws_access_key_id: "your_id"
  #     aws_secret_access_key: "your_key"

DO:
  profiles:
  #   -
  #     name: "name_of_profile"
  #     token: "secretspecialuniquesnowflake"