Local:
  SSH_command: "ssh"
  Static_profiles: "./iTerm2-static-profiles"
  SSH_base_string: "-oStrictHostKeyChecking=no -oUpdateHostKeys=yes -oServerAliveInterval=30 -oAddKeysToAgent=no"
  # Con_username: "ec2-user"
  # Bastion_Con_username: "aviad"
  Bastion: False
  SSH_keys_path: "~/Downloads"
  Use_shared_key: False
  # Login_command: "sudo -i"
  Parallel_exec: True
  Skip_stopped: True
  Badge_info_to_display:
    Name: "Formatted"
    Instance_key: True
    InstanceType: True
    Bastion: False
    Bastion_Con_port: False
    Bastion_Con_username: False
    Con_port: False
    Con_username: False
    Dynamic_profile_parent_name: False
    Group: False
    Id: True
    Instance_use_Bastion: False
    Instance_use_ip_public: False
    Iterm_tags_prefixs: ["ENV"]
    # Iterm_tags_prefixs: []
    Password: False
    Platform: False
    Region: True
    SSH_key: False
    Use_shared_key: False
    VPC: False
    Ip_public: True
  SSH_Config_create: false
  Docker_contexts_create: false

AWS:
  exclude_regions: ["ap-southeast-1", "ap-southeast-2","sa-east-1","ap-northeast-1","ap-northeast-2","ap-south-1"]
  aws_credentials_file: "~/.aws/credentials"
  Con_username: False
  Bastion_Con_port: 22
  Use_ip_public: False
  Skip_stopped: True
  exclude_accounts: []
  use_awscli_profiles: False
  update_hosts: False
  profiles:
    -
      name: "Name_of_company"
      aws_access_key_id: "AKIA****************"
      aws_secret_access_key: "ko1k************************************"
      role_arns: {
        name_of_account1: "arn:aws:iam::438*********:role/iTerm_RO_from_TGT",
        name_of_account2: "arn:aws:iam::168*********:role/iTerm_RO_from_TGT",
        name_of_account3: "arn:aws:iam::701*********:role/iTerm_RO_from_TGT",
      }

DO:
  profiles:
  #   -
  #     name: "The one"
  #     token: "secretspecialuniquesnowflake"
  #     Use_ip_public: True