AWS:
  aws_credentials_file: "~/.aws/credentials"
  static_profiles: "./iTerm2-static-profiles"
  skip_stopped: True
  exclude_accounts: ["default"]
  exclude_regions: [] # for example: ["ap-southeast-1", "ap-southeast-2","sa-east-1","ap-northeast-1","ap-northeast-2","ap-south-1"]