
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install missing python packages
        run: >- 
          sudo apt-get install -y --no-install-recommends python3-venv python3-setuptools
          gcc libpq-dev
          python-dev python-pip
          python3-pip python3-wheel

      - name: Install dependencies with pip + requirements.txt
        run: |
          python3 -m venv .venv
          .venv/bin/pip install -r requirements.txt
      - name: Move the dependencies
        run: mv .venv /home/runner/work/_temp/_github_workflow
      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: docker://github/super-linter:v3.3.1
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          PYTHONPATH: "/github/workspace/:\
            /github/workflow/.venv/lib/python3.6/site-packages"
